# Generated by Django 5.1.6 on 2025-03-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_job_jobapplication_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
    ]
