# Generated by Django 5.1.6 on 2025-03-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='interaction_history',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_locations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_salary_range',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_working_hours',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='skill_weights',
            field=models.JSONField(default=dict),
        ),
    ]
